# Generated by Django 5.1 on 2024-11-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='User_Admin',
        ),
    ]
