# Generated by Django 5.1.3 on 2024-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_rename_admin_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('serial', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('department_id', models.IntegerField()),
                ('access', models.BooleanField(default=False)),
            ],
        ),
    ]
