# Generated by Django 5.1.3 on 2024-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0005_userface'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterFace',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('face_image', models.ImageField(upload_to='user_faces/')),
                ('email', models.EmailField(default=False, max_length=254, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(default=False, max_length=15, unique=True)),
                ('address', models.TextField(default=False)),
                ('department_id', models.IntegerField(default=False)),
                ('access', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UserFace',
        ),
    ]
